version: "3"

services: 

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile-development
    container_name: app
    env_file: .env
    networks: 
      - era
    ports:
      - 3000:3000
    volumes:
      - .:/app


networks:
  era:
    external:
      name: era